apiVersion: apps/v1
kind: Deployment
metadata:
  name: fincore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fincore-app
      version: v1
  template:
    metadata:
      name: fincore-pod
      labels:
        app: fincore-app
        version: v1
    spec:
      containers:
        - name: fincore-container
          image: 10.1.2.58:80/fincore/fincore:v8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
